easy_admin:
    site_name: 'Platform <em style="font-size: 80%;">Training Corp.</em>'
    design:
        menu: [{ entity: 'User', label: 'Users' }, { entity: 'GenderType', label: 'Gender' }, { entity: 'PlatformTrainingSession', label: 'Training Sessions' }]
    entities:
        - App\Entity\User
        - App\Entity\GenderType
        - App\Entity\PlatformTrainingSession
        #PlatformTrainingSession:
         # class: App\Entity\PlatformTrainingSession
          #disabled_actions: ['new']
          #edit:
            #fields:
             #   - trainer
              #  - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_FORMATOR': 'ROLE_FORMATOR' } } }
